### ISSUE TITLE
Help: Make Linux Appear as Windows

### ISSUE THREAD

**Issue by PowerPress** [mushorg/oschameleon#10]
Can this program be used to make a Linux machine appear to be Windows based on network fingerprint? Goal is to run Tor browser with user agent and such showing Windows but prevent the network stack from giving away in Linux. If this can be done do you mind giving an example of how to pull it off with emulating windows networking fingerprint.

**Comment by Atavic** [comment]
See: https://github.com/mushorg/oschameleon/blob/master/oschameleon/template/windows_7_SP1.txt
