### ISSUE TITLE
TypeError: run() takes at most 4 arguments (5 given)

### ISSUE THREAD

**Issue by oojedo2s** [mushorg/oschameleon#12]
I just installed the OSChameleon application few minutes ago and i get the below error message when I try to run it. Kindly help resolve.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "oschameleonRun.py", line 52, in root_process
    data = OSFuscation.run(self.args.public_ip, self.args.debug, self.args.template, self.args.server)
TypeError: run() takes at most 4 arguments (5 given)
<Greenlet at 0x7febd77f8eb0: <bound method OSChameleon.root_process of <__main__.OSChameleon object at 0x7febd77cd9d0>>> failed with TypeError
```

**Comment by glaslos** [comment]
Did a quick fix, please try again with the latest master

**Comment by oojedo2s** [comment]
I tried again with the latest master and now it prints a continuous "callback failure !" until i interrupted it.

callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (3 given)

**Comment by glaslos** [comment]
I update the README, please make sure to use python-nfqueue>=0.6
