### ISSUE TITLE
Doesn't build or install correctly, because of debian package dependency

### ISSUE THREAD

**Issue by scresante** [mushorg/oschameleon#14]
This package depends on the nfqueue module, which is (AFAIK) only provided by a debian package. nfqueue is not in pypi, so it can't be satisfied as a requirement when installing through pip, or with setup.py. 

I'm interested in helping to resolve this issue, and perhaps migrate to a different module for handling nfqueue. I've tweeted pollux (gh@chifflier) about this, and waiting to hear back.

**Comment by glaslos** [comment]
This is mentioned in the README.

**Comment by scresante** [comment]
@glaslos  Yes, I know. That's the problem -- the dependency on debian/ubuntu. 

I spent 2 hours last night trying to come up with a workaround - to manually download the python-nfqueue .deb file, and extract it, and repackage for a different Linux distro, to no avail.

The burden of relying on a debian package to provide a requirement is pretty significant. 

I was wondering how hard would it be to switch to using https://pypi.org/project/fnfqueue/ ?

**Comment by glaslos** [comment]
What Linux distro are you using?
Have you tried building from source? https://github.com/chifflier/nfqueue-bindings
I don't think switching do a different nfqueue library would be too difficult, unfortunately I don't have the time to do so.

**Comment by glaslos** [comment]
How about using an Ubuntu container with `--net=host`?
