### ISSUE TITLE
from parse_fp import get_os_pattern

### ISSUE THREAD

**Issue by indigopsy** [mushorg/oschameleon#6]
``` python
  File "osfuscation.py", line 58, in <module>
    from parse_fp import get_os_pattern
  File "/git/oschameleon/build/lib.linux-x86_64-2.7/oschameleon/parse_fp.py", line 3, in <module>
    import osfuscation
  File "/git/oschameleon/build/lib.linux-x86_64-2.7/oschameleon/osfuscation.py", line 58, in <module>
    from parse_fp import get_os_pattern
```

**Comment by glaslos** [comment]
The traceback is incomplete.

**Comment by indigopsy** [comment]
Can you please write how to install this and run.

i did:
git clone https://github.com/mushorg/oschameleon.git
cd oschameleon

sudo python setup.py install
this is install output:

> running install
> running bdist_egg
> running egg_info
> creating oschameleon.egg-info
> writing requirements to oschameleon.egg-info/requires.txt
> writing oschameleon.egg-info/PKG-INFO
> writing top-level names to oschameleon.egg-info/top_level.txt
> writing dependency_links to oschameleon.egg-info/dependency_links.txt
> writing manifest file 'oschameleon.egg-info/SOURCES.txt'
> reading manifest file 'oschameleon.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*' found under directory 'tests'
> writing manifest file 'oschameleon.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/oschameleon
> copying oschameleon/parse_fp.py -> build/lib.linux-x86_64-2.7/oschameleon
> copying oschameleon/osfuscation.py -> build/lib.linux-x86_64-2.7/oschameleon
> copying oschameleon/**init**.py -> build/lib.linux-x86_64-2.7/oschameleon
> copying oschameleon/SIMATIC_300_PLC.txt -> build/lib.linux-x86_64-2.7/oschameleon
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/oschameleon
> copying build/lib.linux-x86_64-2.7/oschameleon/SIMATIC_300_PLC.txt -> build/bdist.linux-x86_64/egg/oschameleon
> copying build/lib.linux-x86_64-2.7/oschameleon/parse_fp.py -> build/bdist.linux-x86_64/egg/oschameleon
> copying build/lib.linux-x86_64-2.7/oschameleon/osfuscation.py -> build/bdist.linux-x86_64/egg/oschameleon
> copying build/lib.linux-x86_64-2.7/oschameleon/**init**.py -> build/bdist.linux-x86_64/egg/oschameleon
> byte-compiling build/bdist.linux-x86_64/egg/oschameleon/parse_fp.py to parse_fp.pyc
> byte-compiling build/bdist.linux-x86_64/egg/oschameleon/osfuscation.py to osfuscation.pyc
> byte-compiling build/bdist.linux-x86_64/egg/oschameleon/**init**.py to **init**.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying oschameleon.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> creating dist
> creating 'dist/oschameleon-0.1.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing oschameleon-0.1.2-py2.7.egg
> removing '/usr/local/lib/python2.7/dist-packages/oschameleon-0.1.2-py2.7.egg' (and everything under it)
> creating /usr/local/lib/python2.7/dist-packages/oschameleon-0.1.2-py2.7.egg
> Extracting oschameleon-0.1.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
> oschameleon 0.1.2 is already the active version in easy-install.pth
> 
> Installed /usr/local/lib/python2.7/dist-packages/oschameleon-0.1.2-py2.7.egg
> Processing dependencies for oschameleon==0.1.2
> Searching for scapy==2.2.0
> Best match: scapy 2.2.0
> scapy 2.2.0 is already the active version in easy-install.pth
> 
> Using /usr/lib/python2.7/dist-packages
> Finished processing dependencies for oschameleon==0.1.2

then what? 
i tried to start /git/oschameleon/build/lib.linux-x86_64-2.7/oschameleon/osfuscation.py

sudo python osfuscation.py

> Traceback (most recent call last):
>   File "osfuscation.py", line 58, in <module>
>     from parse_fp import get_os_pattern
>   File "/git/oschameleon/build/lib.linux-x86_64-2.7/oschameleon/parse_fp.py", line 3, in <module>
>     import osfuscation
>   File "/git/oschameleon/build/lib.linux-x86_64-2.7/oschameleon/osfuscation.py", line 58, in <module>
>     from parse_fp import get_os_pattern
> ImportError: cannot import name get_os_pattern

**Comment by glaslos** [comment]
See https://github.com/mushorg/oschameleon/issues/5

**Comment by manu-g** [comment]
With what version of nmap does this work?
I tried to run 
`python root_fork.py --template ../oschameleon/SIMATIC_300.txt`
with the template within the project and several samples from the nmap database, but all results from nmap are, that there are too many fingerprints for an exact os detection.

**Comment by glaslos** [comment]
I haven't tested this code in a long time. What are you trying to use this for?

**Comment by manu-g** [comment]
Obfuscating the OS and let it pretend to be a PLC. 
Does oschameleon require specific open/closed ports, that I need to open/close myself?

**Comment by glaslos** [comment]
No, oschameleon sits on the IP stack and gets all packages going out. I have not used it in a long time and it was more a research project, so it might be broken at the moment. Unfortunately I have currently little incentive to improve this project.
