### ISSUE TITLE
running version

### ISSUE THREAD

**Issue by manu-g** [mushorg/oschameleon#7]
I reworked the source structure and got it working for the Siemens 300 PLC. I am working on the extension for usage with all templates in the nma-db, which is not yet complete. 
The current version is not installed in the python package structure (whatever it is really called), but instead run as a normal script. 
Do you want to keep maintaining the project, then I will upload it to this project

**Comment by glaslos** [comment]
I'm definitely interested in your changes. I'd also be interested in collaborating with you on this. If you are interested, you can also take over lead.

**Comment by manu-g** [comment]
Although (or because of ) I have never managed a github project, I am interested in that.
Can you enable the push function, so that i can upload?
I use it in combination with conpot/snare/snap7. Maybe you want to include this to conpot?

**Comment by glaslos** [comment]
The plan was to integrate this into Conpot. Can you create a pull request with your changes?
