### ISSUE TITLE
TypeError 3 parameters expected 2 given.

### ISSUE THREAD

**Issue by SamuelArnold** [mushorg/oschameleon#9]
I am running Kali 2017. I tried to install and use but had some issues. It hangs until an NMAP scan then crashes. asking for another parameter. I am sorry I am a noob when it comes to this. 

![oschameleon error](https://user-images.githubusercontent.com/23040194/28886448-8c2bc996-7787-11e7-94dd-43281d18d8cb.png)
Below Is how I was got to the error

                                        echo "OSChemeleon"
					cp -a ./Bin/oschameleon /opt/oschameleon
					myvar="$PWD"
					cd /opt/oschameleon
					
					apt-get install python-nfqueue
					apt-get install python-scapy
					apt-get install python-gevent
					apt-get install python-netifaces
					echo -e "\e[42m====Install Dependecies Complete!============="
					echo -e "\e[49m"
					
					sudo python /opt/oschameleon/setup.py build
  				        sudo python /opt/oschameleon/setup.py install
					echo -e "\e[42m====Build install Complete!============="
					echo -e "\e[49m"
						
					cd /opt/oschameleon/oschameleon
					sudo python /opt/oschameleon/oschameleon/oschameleonRun.py --template template/SIMATIC_300_PLC.txt
					cd "$myvar"
					echo "===== Complete ======="

**Comment by glaslos** [comment]
Which version of Python and python-nfqueue are you using?

**Comment by divyamadhav** [comment]
Hi, 

I am getting the same error with this program. Can you please tell me how to rectify it .

Thanks

**Comment by glaslos** [comment]
Which version of Python and python-nfqueue are you using?

**Comment by divyamadhav** [comment]
I am using python 2.7 and python-nfqueue version 0.6-1

**Comment by glaslos** [comment]
Fixed in master
